### ISSUE TITLE
貌似用了发热好严重

### ISSUE THREAD

**Issue by AlmostSir777** [Maru-zhang/MARFaceBeauty#3]
博主,您好,我最近试用了你的demo,效果很好,界面也很好看,就是感觉好烧性能,机身会发烫,这个有优化方案吗

**Comment by Maru-zhang** [comment]
请问你用的是什么机型呢，我这边好像没有出现这样的情况

**Comment by AlmostSir777** [comment]
应该是手机性能问题,能不能加你个qq联系下,有些具体用法还不清楚,有些小bug,照相功能被我去除了,还有录制满了15秒后播放了会有bug,我删除影音,界面卡死了,我的QQ:774511860

**Comment by Maru-zhang** [comment]
15S的BUG已经修复了，是我的粗心了，我不太喜欢暴露个人隐私账号，所以有什么问题有什么我能帮的可以在这里说，谢谢了

**Comment by AlmostSir777** [comment]
我也解决了,昨天我琢磨了那些问题,根据我项目去求修改好了,谢谢博主

**Comment by AlmostSir777** [comment]
对了,博主,貌似会出现录制成功保存了,退出录制界面,再次进入录制后此文件夹存在,录制保存不成功,以及播放不出

**Comment by Maru-zhang** [comment]
再进入怎么会文件夹存在呢，我记得每次开始录制的时候都会操作一次unlink的

**Comment by AlmostSir777** [comment]
哦哦,我这录制成功后不播放,保存好到相册看到的是黑屏或者只有一帧图

**Comment by AlmostSir777** [comment]
我这不知道什么影响了,15s的bug没了,但是视频卡住在第一帧,运行博主的demo也是一样,是不是路径问题啊,我录制完跳转到另外的一个界面播放也是卡住的,

**Comment by AlmostSir777** [comment]
博主,貌似是手机问题,我这个手机6P有问题,手机播放视频会卡住,迷之bug,重启就好了

**Comment by Maru-zhang** [comment]
你的手机系统是不是最新的，我发现新系统貌似会有一些莫名其妙的BUG，这些系统级的BUG就很蛋疼了。。。卡住的话你可以追踪一下真机录制的视频文件，然后看看是不是只录制了第一帧。。。

**Comment by AlmostSir777** [comment]
我的手机是10.1的,好,到时候我看下录制的文件

**Comment by AlmostSir777** [comment]
博主,你要修复下iphone5的bug,我用iphone5录制完后运行APP的其他界面很卡,貌似要退出的时候把视频录制的那个关闭,卡顿就好多了
